name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag elmremoting
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Docker tag
      run: docker tag elmremoting aleksandrmelnikov88/gothhub:new
    - name: Docker Push
      run: docker push aleksandrmelnikov88/gothhub:new    
    - name: executing remote ssh commands 
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME2 }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: docker pull aleksandrmelnikov88/gothhub:new
    

